-- Clean Supabase schema rebuild for trading system
-- Generated by Hermes on 2026-05-28
-- Real-data-first: no fake/sample seed rows are inserted.

BEGIN;

-- Drop existing unstable schema objects.
DROP TABLE IF EXISTS
    orders,
    positions,
    trading_signals,
    scalping_snapshots,
    technical_indicators,
    intraday_prices,
    daily_prices,
    kospi_top50
CASCADE;

-- 1. KOSPI TOP50 stock universe / master table
CREATE TABLE kospi_top50 (
    id BIGSERIAL PRIMARY KEY,
    rank INTEGER,
    stock_code VARCHAR(10) NOT NULL UNIQUE,
    stock_name VARCHAR(100),
    market VARCHAR(20) DEFAULT 'KOSPI',
    market_cap BIGINT,
    sector VARCHAR(100),
    volume BIGINT,
    trading_value BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    source VARCHAR(50) DEFAULT 'kiwoom',
    collected_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Daily OHLCV data
-- Keep column names compatible with existing scripts: date/open/high/low/close/volume.
CREATE TABLE daily_prices (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    open NUMERIC(14, 2),
    high NUMERIC(14, 2),
    low NUMERIC(14, 2),
    close NUMERIC(14, 2),
    volume BIGINT,
    trading_value BIGINT,
    foreigner_rate NUMERIC(7, 3),
    source VARCHAR(50) DEFAULT 'kiwoom',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(stock_code, date)
);

-- 3. Intraday/minute/tick data
CREATE TABLE intraday_prices (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    time_frame VARCHAR(20) NOT NULL DEFAULT '1min',
    open NUMERIC(14, 2),
    high NUMERIC(14, 2),
    low NUMERIC(14, 2),
    close NUMERIC(14, 2),
    volume BIGINT,
    trading_value BIGINT,
    bid_price NUMERIC(14, 2),
    ask_price NUMERIC(14, 2),
    bid_volume BIGINT,
    ask_volume BIGINT,
    source VARCHAR(50) DEFAULT 'kiwoom',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(stock_code, timestamp, time_frame)
);

-- 4. Technical indicators
-- Keep ma_5/ma_20/ma_60 names compatible with existing code.
CREATE TABLE technical_indicators (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    time_frame VARCHAR(20) NOT NULL DEFAULT 'daily',
    ma_5 NUMERIC(14, 4),
    ma_20 NUMERIC(14, 4),
    ma_60 NUMERIC(14, 4),
    rsi NUMERIC(8, 4),
    macd NUMERIC(14, 6),
    signal_line NUMERIC(14, 6),
    macd_hist NUMERIC(14, 6),
    bb_upper NUMERIC(14, 4),
    bb_middle NUMERIC(14, 4),
    bb_lower NUMERIC(14, 4),
    atr NUMERIC(14, 4),
    obv BIGINT,
    volume_ma BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(stock_code, date, time_frame)
);

-- 5. Trading signals
-- Includes both legacy/simple fields and score_details JSONB for detailed breakdowns.
CREATE TABLE trading_signals (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
    signal_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    time_frame VARCHAR(20) DEFAULT 'daily',
    price NUMERIC(14, 2),
    price_at_signal NUMERIC(14, 2),
    quantity INTEGER,
    score NUMERIC(8, 4),
    signal_strength NUMERIC(8, 4),
    score_details JSONB DEFAULT '{}'::jsonb,
    reason TEXT,
    strategy VARCHAR(100),
    executed BOOLEAN NOT NULL DEFAULT false,
    executed_at TIMESTAMPTZ,
    executed_price NUMERIC(14, 2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Orders
CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    order_id VARCHAR(80) UNIQUE,
    stock_code VARCHAR(10) NOT NULL,
    order_type VARCHAR(10) NOT NULL CHECK (order_type IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL,
    price NUMERIC(14, 2),
    filled_price NUMERIC(14, 2),
    filled_quantity INTEGER,
    status VARCHAR(30) DEFAULT 'PENDING',
    strategy VARCHAR(100),
    signal_id BIGINT REFERENCES trading_signals(id) ON DELETE SET NULL,
    raw_response JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Positions / account holdings
CREATE TABLE positions (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    avg_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
    current_price NUMERIC(14, 2),
    pnl NUMERIC(14, 2),
    pnl_pct NUMERIC(8, 4),
    realized_pnl NUMERIC(14, 2) DEFAULT 0,
    stop_loss NUMERIC(14, 2),
    take_profit NUMERIC(14, 2),
    status VARCHAR(30) DEFAULT 'OPEN',
    strategy VARCHAR(100),
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Scalping snapshots
CREATE TABLE scalping_snapshots (
    id BIGSERIAL PRIMARY KEY,
    stock_code VARCHAR(10) NOT NULL,
    snapshot_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_price NUMERIC(14, 2),
    price_change_rate NUMERIC(8, 4),
    volume BIGINT,
    volume_ratio NUMERIC(8, 4),
    ma_5 NUMERIC(14, 4),
    ma_20 NUMERIC(14, 4),
    rsi NUMERIC(8, 4),
    bid_ask_ratio NUMERIC(8, 4),
    signal_strength INTEGER,
    decision VARCHAR(20),
    recommendation VARCHAR(20),
    signal_summary TEXT,
    raw_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_kospi_top50_rank ON kospi_top50(rank);
CREATE INDEX idx_kospi_top50_active ON kospi_top50(is_active, rank);
CREATE INDEX idx_daily_prices_stock_date ON daily_prices(stock_code, date DESC);
CREATE INDEX idx_intraday_prices_stock_time ON intraday_prices(stock_code, timestamp DESC);
CREATE INDEX idx_technical_stock_date ON technical_indicators(stock_code, date DESC, time_frame);
CREATE INDEX idx_signals_stock_date ON trading_signals(stock_code, signal_date DESC);
CREATE INDEX idx_signals_type_date ON trading_signals(signal_type, signal_date DESC);
CREATE INDEX idx_orders_stock_created ON orders(stock_code, created_at DESC);
CREATE INDEX idx_orders_status ON orders(status, created_at DESC);
CREATE INDEX idx_positions_status ON positions(status, stock_code);
CREATE INDEX idx_scalping_stock_time ON scalping_snapshots(stock_code, snapshot_time DESC);

-- RLS enabled. Service-role key bypasses RLS; anon only gets read access to market data.
ALTER TABLE kospi_top50 ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE intraday_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE technical_indicators ENABLE ROW LEVEL SECURITY;
ALTER TABLE trading_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE scalping_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY kospi_top50_anon_select ON kospi_top50 FOR SELECT TO anon USING (true);
CREATE POLICY daily_prices_anon_select ON daily_prices FOR SELECT TO anon USING (true);
CREATE POLICY intraday_prices_anon_select ON intraday_prices FOR SELECT TO anon USING (true);
CREATE POLICY technical_indicators_anon_select ON technical_indicators FOR SELECT TO anon USING (true);

CREATE POLICY authenticated_all_kospi_top50 ON kospi_top50 FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_daily_prices ON daily_prices FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_intraday_prices ON intraday_prices FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_technical_indicators ON technical_indicators FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_trading_signals ON trading_signals FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_orders ON orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_positions ON positions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY authenticated_all_scalping_snapshots ON scalping_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);

COMMIT;
