import sys
import os

backup_path = '/home/june/trading/core/fujimoto_126_filter.py.backup'
target_path = '/home/june/trading/core/fujimoto_126_filter.py'

with open(backup_path, 'r') as f:
    lines = f.readlines()

# Find the start and end indices of the simulate_fujimoto_126_trade function.
start = -1
for i, line in enumerate(lines):
    if line.strip().startswith('def simulate_fujimoto_126_trade('):
        start = i
        break

if start == -1:
    print("ERROR: Could not find simulate_fujimoto_126_trade function in backup")
    sys.exit(1)

# Find the end of the function: look for the next line that starts with 'def ' or 'class ' (after stripping) after start.
end = len(lines)
for i in range(start + 1, len(lines)):
    stripped = lines[i].strip()
    if stripped.startswith('def ') or stripped.startswith('class '):
        end = i
        break

# Now we have the function from lines[start:end]
# Define the new function as a list of strings (each line ends with newline)
new_func = [
    'def simulate_fujimoto_126_trade(\n',
    '    bars: list[PriceBar],\n',
    '    *,\n',
    '    min_score: float = 60.0,\n',
    '    stop_loss_pct: float = -1.0,  # user requested -1%\n',
    '    take_profit_pct: float = 3.0,\n',
    '    take_profit_half_pct: float = 5.0,  # additional forced exit at +5% for remaining half\n',
    '    time_exit: str = "15:20",\n',
    '    max_holding_days: int = 3,  # swing trading basis: max 3 days\n',
    '    fee_bps: float = 23.0,\n',
    '    slippage_bps: float = 10.0,\n',
    ') -> dict[str, Any]:\n',
    '    """Simulate read-only intraday trades with multiple entries allowed, across multiple days.\n',
    '    Rules:\n',
    '    - Entry: when evaluate_fujimoto_126 returns signal == HIGH_CONFIDENCE_CANDIDATE.\n',
    '    - Position size: 1 unit per entry (we treat each entry as size 1.0 for simplicity).\n',
    '    - Stop loss: -2% from entry price (configurable).\n',
    '    - Take profit: +3% from entry price -> exit 50% of position at that price.\n',
    '    - Remaining 50%: stop loss moved to break-even (entry price) and forced exit at +5% from entry.\n',
    '    - Time exit: close all remaining at time_exit (HH:MM) each day.\n',
    '    - Max holding days: close all remaining after max_holding_days have passed since entry.\n',
    '    - Re-entry allowed after a position is fully closed.\n',
    '    Returns aggregated trade statistics.\n',
    '    """\n',
    '    if not bars:\n',
    '        return {"ok": False, "blocking_conditions": ["missing_intraday_bars", *ORDER_BLOCKS], "paper_order_allowed": False, "real_order_allowed": False, "order_execution_enabled": False}\n',
    '\n',
    '    # State\n',
    '    in_position = False\n',
    '    entry_price = 0.0\n',
    '    entry_dt = None  # datetime of entry bar\n',
    '    remaining = 0.0  # fraction of position size still open (0 to 1)\n',
    '    # Levels based on entry price\n',
    '    stop_loss_price = 0.0\n',
    '    target_price = 0.0          # +3% target\n',
    '    target_half_price = 0.0     # +5% target for remaining half\n',
    '    # Trade logs\n',
    '    trade_chunks = []  # each dict: {entry_price, entry_time, exit_price, exit_time, reason, size}\n',
    '\n',
    '    i = 0\n',
    '    n = len(bars)\n',
    '    while i < n:\n',
    '        bar = bars[i]\n',
    '        # Evaluate signal up to current bar\n',
    '        window = bars[: i + 1]\n',
    '        eval_result = evaluate_fujimoto_126(window, min_score=min_score)\n',
    '        signal = eval_result.get("signal", "")\n',
    '\n',
    '        if not in_position and signal == "HIGH_CONFIDENCE_CANDIDATE":\n',
    '            # Enter position\n',
    '            in_position = True\n',
    '            entry_price = float(bar.close) if bar.close is not None else 0.0\n',
    '            entry_dt = bar.ts\n',
    '            remaining = 1.0\n',
    '            # Initialize levels\n',
    '            stop_loss_price = entry_price * (1.0 + stop_loss_pct / 100.0)\n',
    '            target_price = entry_price * (1.0 + take_profit_pct / 100.0)\n',
    '            target_half_price = entry_price * (1.0 + take_profit_half_pct / 100.0)\n',
    '\n',
    '        if in_position and entry_price > 0 and entry_dt is not None:\n',
    '            high = float(bar.high) if bar.high is not None else 0.0\n',
    '            low = float(bar.low) if bar.low is not None else 0.0\n',
    '            close = float(bar.close) if bar.close is not None else 0.0\n',
    '            time = bar.hhmm\n',
    '            cur_dt = bar.ts\n',
    '\n',
    '            # Check max holding days\n',
    '            if remaining > 0:\n',
    '                days_held = (cur_dt - entry_dt).total_seconds() / (24 * 3600)\n',
    '                if days_held >= max_holding_days:\n',
    '                    # Exit all remaining at close price\n',
    '                    trade_chunks.append({\n',
    '                        "entry_price": entry_price,\n',
    '                        "entry_time": entry_dt.strftime(\'%H:%M\'),\n',
    '                        "exit_price": close,\n',
    '                        "exit_time": time,\n',
    '                        "reason": "MAX_HOLDING_DAYS",\n',
    '                        "size": remaining,\n',
    '                    })\n',
    '                    remaining = 0.0\n',
    '                    in_position = False\n',
    '                    # After exit, continue to next bar (do not skip)\n',
    '                    i += 1\n',
    '                    continue\n',
    '\n',
    '            # Check stop loss\n',
    '            if remaining > 0 and low <= stop_loss_price:\n',
    '                # Exit all remaining at stop loss price\n',
    '                trade_chunks.append({\n',
    '                    "entry_price": entry_price,\n',
    '                    "entry_time": entry_dt.strftime(\'%H:%M\'),\n',
    '                    "exit_price": stop_loss_price,\n',
    '                    "exit_time": time,\n',
    '                    "reason": "STOP_LOSS",\n',
    '                    "size": remaining,\n',
    '                })\n',
    '                remaining = 0.0\n',
    '                in_position = False\n',
    '                # After exit, we will look for next signal in next iteration\n',
    '                i += 1\n',
    '                continue\n',
    '            # Check take profit (first half) only if we still have full position\n',
    '            elif remaining == 1.0 and high >= target_price:\n',
    '                # Exit 50% at target price\n',
    '                trade_chunks.append({\n',
    '                    "entry_price": entry_price,\n',
    '                    "entry_time": entry_dt.strftime(\'%H:%M\'),\n',
    '                    "exit_price": target_price,\n',
    '                    "exit_time": time,\n',
    '                    "reason": "TARGET_HALF",\n',
    '                    "size": 0.5,\n',
    '                })\n',
    '                remaining = 0.5\n',
    '                # Adjust stop loss to break-even and set target to forced exit at +5%\n',
    '                stop_loss_price = entry_price  # break-even\n',
    '                target_price = target_half_price  # now target is the forced exit at +5%\n',
    '            # Check forced exit at +5% for remaining half\n',
    '            elif remaining == 0.5 and high >= target_half_price:\n',
    '                trade_chunks.append({\n',
    '                    "entry_price": entry_price,\n',
    '                    "entry_time": entry_dt.strftime(\'%H:%M\'),\n',
    '                    "exit_price": target_half_price,\n',
    '                    "exit_time": time,\n',
    '                    "reason": "TARGET_FULL",\n',
    '                    "size": remaining,\n',
    '                })\n',
    '                remaining = 0.0\n',
    '                in_position = False\n',
    '            # Check time exit (intraday)\n',
    '            elif time >= time_exit:\n',
    '                # Exit all remaining at close price\n',
    '                exit_price = close if close > 0 else entry_price  # fallback to entry price if close invalid\n',
    '                trade_chunks.append({\n',
    '                    "entry_price": entry_price,\n',
    '                    "entry_time": entry_dt.strftime(\'%H:%M\'),\n',
    '                    "exit_price": exit_price,\n',
    '                    "exit_time': time,\n',
    '                    "reason": "TIME_EXIT",\n',
    '                    "size": remaining,\n',
    '                })\n',
    '                remaining = 0.0\n',
    '                in_position = False\n',
    '            # If price moves but no exit condition, we continue holding\n',
    '\n',
    '        i += 1\n',
    '\n',
    '    # After loop, if still in position, close at last close\n',
    '    if in_position and remaining > 0 and entry_price > 0:\n',
    '        close_price = float(bars[-1].close) if bars[-1].close is not None else entry_price\n',
    '        trade_chunks.append({\n',
    '            "entry_price": entry_price,\n',
    '            "entry_time": entry_dt.strftime(\'%H:%M\') if entry_dt else "",\n',
    '            "exit_price": close_price,\n',
    '            "exit_time": bars[-1].hhmm,\n',
    '            "reason": "END_OF_DATA",\n',
    '            "size": remaining,\n',
    '        })\n',
    '        remaining = 0.0\n',
    '        in_position = False\n',
    '\n',
    '    # If no trades occurred, return blocked with eval of full series\n',
    '    if not trade_chunks:\n',
    '        final_eval = evaluate_fujimoto_126(bars, min_score=min_score)\n',
    '        return {"ok": False, **final_eval}\n',
    '\n',
    '    # Compute aggregated statistics\n',
    '    total_size = sum(tc["size"] for tc in trade_chunks)\n',
    '    total_cost = 0.0\n',
    '    total_gross = 0.0\n',
    '    for tc in trade_chunks:\n',
    '        entry = tc["entry_price"]\n',
    '        exitp = tc["exit_price"]\n',
    '        size = tc["size"]\n',
    '        if entry > 0:\n',
    '            gross = (exitp - entry) / entry * 100.0\n',
    '            total_gross += gross * size\n',
    '            # Cost per unit: round-trip fee + slippage\n',
    '            cost_per_unit = ((fee_bps + slippage_bps) / 100.0) * 2.0\n',
    '            total_cost += cost_per_unit * size\n',
    '        else:\n',
    '            # invalid entry price, treat as zero gross\n',
    '            pass\n',
    '\n',
    '    if total_size > 0:\n',
    '        avg_gross = total_gross / total_size\n',
    '        avg_cost = total_cost / total_size\n',
    '        net = avg_gross - avg_cost\n',
    '    else:\n',
    '        avg_gross = 0.0\n',
    '        avg_cost = 0.0\n',
    '        net = 0.0\n',
    '\n',
    '    # Determine overall signal: if any trade was profitable? We\\'ll just set based on last trade? \n',
    '    # For simplicity, we keep signal as HIGH_CONFIDENCE_CANDIDATE if we had any trades.\n',
    '    signal = "HIGH_CONFIDENCE_CANDIDATE" if trade_chunks else "BLOCKED"\n',
    '\n',
    '    return {\n',
    '        "ok": True,\n',
    '        "strategy": STRATEGY_ID,\n',
    '        # For compatibility with existing expectations, we keep these fields from the last trade?\n',
    '        # We\\'ll set to the first trade\\'s entry details for simplicity.\n',
    '        "entry_time": trade_chunks[0]["entry_time"] if trade_chunks else "",\n',
    '        "entry_price": _round(trade_chunks[0]["entry_price"]) if trade_chunks else 0,\n',
    '        "entry_stage": "UNKNOWN",  # we could compute but skip\n',
    '        "position_units": 0,  # not applicable\n',
    '        "entry_score_total": 0.0,  # we could average but skip\n',
    '        "entry_score_details": {},\n',
    '        "exit_time": trade_chunks[-1]["exit_time"] if trade_chunks else "",\n',
    '        "exit_price": _round(trade_chunks[-1]["exit_price"]) if trade_chunks else 0,\n',
    '        "exit_reason": trade_chunks[-1]["reason"] if trade_chunks else "",\n',
    '        "gross_return_pct": _round(avg_gross),\n',
    '        "cost_pct": _round(avg_cost),\n',
    '        "net_return_pct": _round(net),\n',
    '        "blocking_conditions": [],  # no blocking conditions if we have trades\n',
    '        "paper_order_allowed": False,\n',
    '        "real_order_allowed": False,\n',
    '        "order_execution_enabled": False,\n',
    '    }\n',
]

# Now construct new lines: everything before start, then new_func, then everything from end onwards.
new_lines = lines[:start] + new_func + lines[end:]

# Write to target
with open(target_path, 'w') as f:
    f.writelines(new_lines)

print("SUCCESS: Updated simulate_fujimoto_126_trade function")